baseURL = "https://theologique.ch/"
title = "theologique.ch"

defaultContentLanguage = "fr"
languageCode = "fr"

cleanDestinationDir = true
disableFastRender = true
enableGitInfo = true
noBuildLock = true
removePathAccents = true

copyright = "Creative Commons Zero"

disableKinds = [ "robotsTXT", "taxonomy", "term" ]

summaryLength = 30

[frontmatter]
date = ["date", ":git"]
lastmod = ["lastmod", ":git"]

[markup.goldmark.parser]
autoHeadingIDType = "github-ascii"

[minify]
minifyOutput = true

[minify.tdewolff.html]
keepDefaultAttrVals = false
keepEndTags = true
keepQuotes = true
keepWhitespace = true

[params]
[params.author]
name = "Nicolas Friedli"
email = "contact+rss@theologique.ch"