baseURL = "https://theologique.ch/"
title = "theologique.ch"

defaultContentLanguage = "fr"
languageCode = "fr"

cleanDestinationDir = true
disableFastRender = true
enableGitInfo = true
noBuildLock = true
removePathAccents = true

copyright = "Creative Commons Zero"

disableKinds = [ "404", "robotsTXT", "RSS", "taxonomy", "term" ]

[frontmatter]
date = ["date", ":git"]
lastmod = ["lastmod", ":git"]

[markup.goldmark.parser]
autoHeadingIDType = "github-ascii"

[minify]
minifyOutput = true

[minify.tdewolff.html]
keepDefaultAttrVals = false
keepEndTags = true
keepQuotes = true
keepWhitespace = true

[params]
footer = """Le responsable bénévole de l’annuaire est [Nicolas Friedli](https://nicolasfriedli.ch/). Les sources sont disponibles sur [GitHub](https://github.com/nfriedli/theologique.ch). theologique.ch respecte votre vie privée. Il est servi par un hébergeur écoresponsable.

Seuls les sites qui disposent de leur propre nom de domaine (ou d'un sous-domaine) sont ajoutés. Les sites des paroisses et des régions ne sont pas référencés. Les propriétaires des sites peuvent demander le retrait de leur site. La description est produite par theologique.ch.
"""

[params.author]
name = "Nicolas Friedli"
email = "contact+rss@theologique.ch"

[taxonomies]
tag = "tags"