baseURL = "https://theologique.ch/"
title = "theologique.ch"

defaultContentLanguage = "fr"
languageCode = "fr"

cleanDestinationDir = true
disableFastRender = true
enableGitInfo = true
noBuildLock = true
removePathAccents = true

# ne pas ajouter de majuscule aux tags (pour le titre)
titleCaseStyle = "none" 

copyright = "Creative Commons Zero"

disableKinds = [ "robotsTXT" ]

summaryLength = 30

[frontmatter]
date = ["date", ":git"]
lastmod = ["lastmod", ":git"]

[markup.goldmark.parser]
autoHeadingIDType = "github-ascii"

[minify]
minifyOutput = true

[minify.tdewolff.html]
keepDefaultAttrVals = false
keepEndTags = true
keepQuotes = true
keepWhitespace = true

[params]
[params.author]
name = "Nicolas Friedli"
email = "contact+rss@theologique.ch"

[related]
includeNewer = true
threshold = 50
toLower = true
[[related.indices]]
name = "tags"
weight = 80
[[related.indices]]
name = "keywords"
weight = 40
[[related.indices]]
name = "editors"
weight = 100

[taxonomies]
tag = "tags"